apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/rabbitmq/messaging-topology-operator/releases/download/v1.18.1/messaging-topology-operator.yaml
  - queues.yml
  - ha-policy.yml
  - rabbitmq-admin-secret.yml
  - users.yml
  - permissions.yml
