apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: valkey-staging
  namespace: argocd
spec:
  project: staging
  source:
    repoURL: https://valkey.io/valkey-helm/
    targetRevision: 0.9.3
    chart: valkey
    helm:
      values: |
        fullnameOverride: "valkey"
  destination:
    namespace: valkey
    name: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: valkey-prod
  namespace: argocd
spec:
  project: prod
  source:
    repoURL: https://valkey.io/valkey-helm/
    targetRevision: 0.9.3
    chart: valkey
  destination:
    namespace: valkey
    name: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true