---
apiVersion: v1
kind: Service
metadata:
  name: llsp-api-service
  namespace: fia
spec:
  selector:
    app: llsp-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
